version: "3.9"
services:
  app:
    image: todoapp:latest
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd123
      - POSTGRES_DB=postgres
